#!/bin/sh

/bin/busybox test ! -e /proc/cpuinfo && /bin/busybox mount -t proc none /proc
/bin/busybox test ! -e /sys/kernel && /bin/busybox mount -t sysfs none /sys
/bin/busybox test ! -e /bin/cp && /bin/busybox --install -s

progress() {
  if test -f /proc/splash; then
    echo "show $1" > /proc/splash
  fi
}

count=0
for script in /etc/init.d/*; do
  count=$(($count+1));
done

pos=47000
step=$(((65535-$pos)/$count))

for script in /etc/init.d/*; do
  pos=$(($pos+$step))
  progress $pos
  /bin/sh $script
done
