#!/bin/sh

/bin/busybox test ! -e /proc/cpuinfo && /bin/busybox mount -t proc none /proc
/bin/busybox test ! -e /bin/cp && /bin/busybox --install -s

progress() {
  if test -f /proc/splash; then
    echo "show $1" > /proc/splash
  fi
  echo "### $2 ###"
}

/bin/sh /etc/init.d/eject &
/bin/sh /etc/init.d/fonts

progress 47000 "launching modules"
/bin/sh /etc/init.d/modules

progress 51000 "setting tv-out"
/bin/sh /etc/init.d/tvout

progress 53000 "setting volume"
/bin/sh /etc/init.d/alsa

progress 55000 "setting up tv card"
/bin/sh /etc/init.d/tvcard

progress 58000 "launching lirc daemon"
/bin/sh /etc/init.d/lirc

progress 60000 "setting up networking"
/bin/sh /etc/init.d/networking &

progress 63000 "setting cdrom speed"
/bin/sh /etc/init.d/cdspeed

test "$DEBUG" = yes || rm -rf /lib/modules

progress 65535 "launching mplayer"
/bin/sh /etc/init.d/mplayer

/bin/sh /etc/init.d/umount
