#!/bin/sh

. config/options
get_meta $1

cd $PKG_BUILD_DIR

touch NEWS AUTHORS ChangeLog

do_autoconf

setup_toolchain target 
CXXFLAGS="-DZLIB_INTERNAL=1" ./configure --prefix=/usr/share/xbmc \
                                         --host=$TARGET_NAME \
                                         --build=$HOST_NAME \
                                         --disable-static \
                                         --enable-shared

make
make_install
