#!/bin/sh
#
# mount samba shares

if test -x /usr/bin/smbmount -a -x /usr/bin/mount.cifs; then
  echo "### Mounting Samba shares ###"
  (
  OPT="-N"
  test -n "$SMB_USER" && OPT="-U$SMB_USER%$SMB_PWD"
  saveifs=$IFS
  IFS='
'
  for i in `smbtree $OPT`; do
    IFS=$saveifs
    mkdir -p "/mnt/shares/$i"
    mount.cifs "//$i" "/mnt/shares/$i" -o ro,username=$SMB_USER,passwd=$SMB_PWD >/dev/null 2>&1 || smbmount "//$i" "/mnt/shares/$i" -o ro,username=$SMB_USER,passwd=$SMB_PWD >/dev/null 2>&1 || rmdir -p "/mnt/shares/$i" >/dev/null 2>&1
    IFS='
'
  done
  IFS=$saveifs
  )&
fi

exit 0
