#!/bin/sh
#
# only keep debugging info if booted in DEBUG mode

if [ "$DEBUG" != yes ]; then
  echo "### Remove debugging info ###"
  rm -rf /lib/modules
  echo 0 > /proc/sys/kernel/printk
fi

exit 0
