#!/bin/sh
#
# start MPlayer's utilities

echo "### Starting MPlayer's utilities ###"

# create the mplayer control pipe for external programs
mkfifo /var/mp_control

# start the autolaunching script
if test -e /usr/bin/autolaunch; then
  sh /usr/bin/autolaunch > /var/mp_control &
fi

# start the file copy daemon
/usr/bin/cpd &

exit 0
