#!/bin/sh
#
# start a debugging shell if booted in DEBUG mode

# give a shell to MPlayer in debug mode
if test "$DEBUG" = yes; then
  echo "### Starting debugging shell ###"
  sed -i 's%ok=\"quit 166\"/>%ok=\"quit 166\"/>  <e name=\"Console\" ok=\"set_menu console\"/>%' /etc/mplayer/menu.conf
  /bin/sh
fi

# remove debugging info
rm -rf /lib/modules
echo 0 > /proc/sys/kernel/printk

# disable console blanking and cursor blinking for a proper MPlayer start
echo -e "\033[9;0]"
echo -e "\033[?25l"

exit 0
