#!/bin/sh
#
# setup alsa (especially the mixer config)

# include audio configuration file
. /etc/audio

echo "" > /etc/asound.conf

# set common mixer params
amixer sset Master 90% on >/dev/null 2>&1
amixer sset PCM 90% on >/dev/null 2>&1
amixer sset Surround 90% on >/dev/null 2>&1
amixer sset 'Surround Digital' 90% on >/dev/null 2>&1
amixer sset 'Wave Surround' 90% on >/dev/null 2>&1
amixer sset 'Duplicate Front' on >/dev/null 2>&1
amixer sset 'Sigmatel 4-Speaker Stereo' 90% on >/dev/null 2>&1
amixer sset 'Headphone' 90% on >/dev/null 2>&1
amixer sset 'Line' 90% on >/dev/null 2>&1
amixer sset 'Aux' 90% on >/dev/null 2>&1

# set SPDIF mixer params
if test "$SPDIF" = yes; then
  amixer sset 'IEC958' 90% on >/dev/null 2>&1
  amixer sset 'IEC958 Output' 90% on >/dev/null 2>&1
  amixer sset 'IEC958 Playback AC97-SPSA' 100% on >/dev/null 2>&1
  amixer sset 'IEC958 Coaxial' 90% on >/dev/null 2>&1
  amixer sset 'IEC958 LiveDrive' 90% on >/dev/null 2>&1
  amixer sset 'IEC958 Optical Raw' 90% on >/dev/null 2>&1
  amixer sset 'SB Live Analog/Digital Output Jack' 90% on >/dev/null 2>&1
fi

# output in 48KHz for VIA VT8233 or SiS 7012
if test -n "`grep 'Class 0401:.*1106:3059' /proc/pci`" \
     -o -n "`grep 'Class 0401:.*1039:7012' /proc/pci`"; then
  echo "srate=48000" >> /etc/mplayer/mplayer.conf
fi

# force output to 44.1KHz for Ensoniq ES137{0,1,3} (SB PCI64/128)
if test -n "`grep 'Class 0401:.*1274:5000' /proc/pci`" \
     -o -n "`grep 'Class 0401:.*1274:5880' /proc/pci`" \
     -o -n "`grep 'Class 0401:.*1274:1371' /proc/pci`"; then
  echo "srate=44100" >> /etc/mplayer/mplayer.conf
fi

exit 0
