#!/bin/sh
#
# setup alsa (especially the mixer config)


echo "" > /etc/asound.conf

# set common mixer params
amixer sset Master 90% on >/dev/null 2>&1
amixer sset PCM 90% on >/dev/null 2>&1
amixer sset Surround 90% on >/dev/null 2>&1
amixer sset 'Surround Digital' 90% on >/dev/null 2>&1
amixer sset 'Wave Surround' 90% on >/dev/null 2>&1
amixer sset 'Duplicate Front' on >/dev/null 2>&1
amixer sset 'Sigmatel 4-Speaker Stereo' 90% on >/dev/null 2>&1
amixer sset 'Headphone' 90% on >/dev/null 2>&1
amixer sset 'Line' 90% on >/dev/null 2>&1
amixer sset 'Aux' 90% on >/dev/null 2>&1

# avoid setting IEC958 Output with CMI8738
if test -z "`grep 'Class 0401:.*10b9:0111' /proc/pci`" \
     -a -z "`grep 'Class 0401:.*13f6:0111' /proc/pci`" \
     -a -z "`grep 'Class 0401:.*13f6:0211' /proc/pci`"; then
  amixer sset 'IEC958 Output' 90% on >/dev/null 2>&1
fi

# output in 48KHz for VIA VT8233 or SiS 7012
if test -n "`grep 'Class 0401:.*1106:3059' /proc/pci`" \
     -o -n "`grep 'Class 0401:.*1039:7012' /proc/pci`"; then
  echo "srate=48000" >> /etc/mplayer.conf
fi

exit 0
