#!/bin/sh
#
# setup tv cards


# bt8x8 Card
if test -n "`grep 'Class 0400:.*109e:' /proc/pci`"; then
  . /etc/tvsettings

  # Setting up BTTV module
  if test "$TV_CARD" = "AUTO"; then # Autodetection
    insmod bttv >/dev/null 2>&1
    insmod tuner >/dev/null 2>&1
    if test -z "`dmesg | grep \"bttv0: detected\"`"; then # Not autodetected
      rmmod bttv
      rmmod tuner
      insmod bttv card=1 >/dev/null 2>&1 
      insmod tuner type=3 >/dev/null 2>&1
    fi
    if test "$TV_TUNER" != "AUTO"; then # Force TV Tuner
      rmmod tuner
      insmod tuner type=$TV_TUNER >/dev/null 2>&1 
    fi
  else # Force TV Card/Tuner
    insmod bttv card=$TV_CARD >/dev/null 2>&1 
    insmod tuner type=$TV_TUNER >/dev/null 2>&1 
  fi

  insmod btcx-risc >/dev/null 2>&1
  insmod videodev >/dev/null 2>&1
  insmod video-buf >/dev/null 2>&1
  insmod tvaudio >/dev/null 2>&1
  insmod v4l1-compat >/dev/null 2>&1
  insmod v4l2-common >/dev/null 2>&1
  insmod msp3400 >/dev/null 2>&1
  insmod tda7432 >/dev/null 2>&1
  insmod tda9875 >/dev/null 2>&1
  insmod tda9887 >/dev/null 2>&1

  # set mplayer TV options for Brooktree cards
  echo "tv=driver=v4l2:chanlist=$CHANLIST:width=768:height=576" >> /etc/mplayer/mplayer.conf
  echo "<cmdlist name=\"tv_chan\" title=\"TV Channels\" ptr=\"<>\" >" >> /etc/mplayer/menu.conf
  grep '^CHAN' /etc/tvsettings | sed 's/^CHAN="\(.*\)":"\(.*\)"/<e name=\"\1\" ok=\"loadfile tv:\/\/\2\"\/>/' >> /etc/mplayer/menu.conf
  echo "</cmdlist>" >> /etc/mplayer/menu.conf
else
  sed 's/.*ok="set_menu tv_settings".*//' /etc/mplayer/menu.conf > /etc/mplayer/menu.conf.new && mv /etc/mplayer/menu.conf.new /etc/mplayer/menu.conf
fi

exit 0
