#!/bin/sh
#
# eject CD if booted from cdrom and their is no media files on it


if test -n "$CDROM"; then
  # add recognized files extension to the EXTS list
  for i in `cat /etc/file_ext`; do
    if [ -z "$EXTS" ]; then
        EXTS="$i"
    else
        EXTS="$EXTS\|$i"
    fi
  done
  # add recognized playlists extension to the EXTS list
  for i in `cat /etc/list_ext`; do EXTS="$EXTS\|$i"; done
  # check if their is recognized media files on the CD
  if test -z "`find "$CDROM" | grep -v /GEEXBOX/ | grep -i "\.\($EXTS\)\$"`"; then
    test -f /proc/progress && echo "86 ejecting GeeXboX CD" > /proc/progress
    # eject the CD (except when started with make exec)
    test -e /dev/cdrom -a ! -f /EXEC && eject &
  fi
fi

exit 0
