#!/bin/sh
#
# put the right font in the right place


# set menu and help files according to language setting
if test -f /etc/lang; then
  LANG=`cat /etc/lang | sed 's/^\([a-z]*\).*/\1/'`

  cp -f /etc/mplayer/menu_$LANG.conf /etc/mplayer/menu.conf
  cp -f /usr/share/mplayer/help_$LANG.txt /usr/share/mplayer/help.txt

  # Language which require `bitmap font` for menu displaying
  if test $LANG = hu; then
    MENU_FONT="/usr/share/mplayer/font/iso-8859-2/font.desc"
  elif test $LANG = he; then
    MENU_FONT="/usr/share/mplayer/font/iso-8859-8/font.desc"
  elif test $LANG = bg; then
    MENU_FONT="/usr/share/mplayer/font/cp1251/font.desc"
  elif test $LANG = ru; then
    MENU_FONT="/usr/share/mplayer/font/koi8r/font.desc"
  else
    # All the other languages (br/cat/cz/de/en/es/fi/fr/it/nl/po/ro/se/sk)
    # who dont require bitmap font, and can use the theme font.
    MENU_FONT="/usr/share/mplayer/font/font.ttf"
  fi

  echo "font=$MENU_FONT" >> /etc/mplayer/mplayer.conf
fi

# set subtitles font according to subfont setting
if test -f /etc/subfont; then
  SUB_FONT=`cat /etc/subfont`

  if test $SUB_FONT = iso-8859-2 -o $SUB_FONT = cz -o $SUB_FONT = hu -o $SUB_FONT = pl -o $SUB_FONT = ro -o $SUB_FONT = sk; then
    SUB_FONT="/usr/share/mplayer/font/iso-8859-2/font.desc"
  elif test $SUB_FONT = iso-8859-8 -o $SUB_FONT = he; then
    SUB_FONT="/usr/share/mplayer/font/iso-8859-8/font.desc"
  elif test $SUB_FONT = cp1251 -o $SUB_FONT = bg; then
    SUB_FONT="/usr/share/mplayer/font/cp1251/font.desc"
  elif test $SUB_FONT = koi8r -o $SUB_FONT = ru; then
    SUB_FONT="/usr/share/mplayer/font/koi8r/font.desc"
  else
    SUB_FONT="/usr/share/mplayer/font/iso-8859-1/font.desc"
  fi

  echo "subfont=$SUB_FONT" >> /etc/mplayer/mplayer.conf
fi

exit 0
