#!/bin/sh
#
# put the right font in the right place


# select the font depending on the language
if test -f /etc/lang; then
  LANG=`cat /etc/lang | sed 's/^\([a-z]*\).*/\1/'`
  cp -f /etc/mplayer/menu_$LANG.conf /etc/mplayer/menu.conf
  cp -f /usr/share/mplayer/help_$LANG.txt /usr/share/mplayer/help.txt
  if test $LANG = cz -o $LANG = hu -o $LANG = sk; then
    mv /usr/share/mplayer/font/iso-8859-2/* /usr/share/mplayer/font
  elif test $LANG = pl; then
    mv /usr/share/mplayer/font/cp1250/* /usr/share/mplayer/font
  elif test $LANG = bg; then
    mv /usr/share/mplayer/font/cp1251/* /usr/share/mplayer/font
  elif test $LANG = ru; then
    mv /usr/share/mplayer/font/koi8r/* /usr/share/mplayer/font
  else
    mv /usr/share/mplayer/font/iso-8859-1/* /usr/share/mplayer/font
  fi
  if test $LANG = hu; then
    sed 's/.*font.*//' /etc/mplayer/mplayer.conf >/etc/mplayer/mplayer.conf.new
    mv /etc/mplayer/mplayer.conf.new /etc/mplayer/mplayer.conf
  fi
fi

# also use the bitmap font for the menu when it's not iso-8859-*
grep iso-8859 /usr/share/mplayer/font/font.desc >/dev/null 2>&1 || (sed 's/.*font.*//' /etc/mplayer/mplayer.conf > /etc/mplayer/mplayer.conf.new; mv /etc/mplayer/mplayer.conf.new /etc/mplayer/mplayer.conf)

exit 0
