#!/bin/sh
#
# put the right font in the right place

. /etc/lang.conf
. /etc/lang.funcs

# set menu and help files according to language setting
if test -f /etc/lang; then
  LANG=`cat /etc/lang | sed 's/^\([a-z]*\).*/\1/'`

  cp -f /etc/mplayer/menu_$LANG.conf /etc/mplayer/menu.conf
  cp -f /usr/share/mplayer/help_$LANG.txt /usr/share/mplayer/help.txt

  MENU_FONT=`lang2menufont $LANG`

  # If language doesn't require bitmap font, use ttf font
  if [ -n "$MENU_FONT" ]; then
    MENU_FONT="/usr/share/mplayer/font/$MENU_FONT/font.desc"
  else
    MENU_FONT="/usr/share/mplayer/font/font.ttf"
  fi

  echo "font=$MENU_FONT" >> /etc/mplayer/mplayer.conf
fi

# set subtitles font according to subfont setting
if test -f /etc/subfont; then
  SUB_FONT=`cat /etc/subfont`
  SUB_FONT=`subfont2font $SUB_FONT`

  font2mpsettings $SUB_FONT >> /etc/mplayer/mplayer.conf

  SUB_FONT="/usr/share/mplayer/font/$SUB_FONT/font.desc"
  [ ! -f "$SUB_FONT" ] && exit 1

  echo "subfont=$SUB_FONT" >> /etc/mplayer/mplayer.conf
fi

exit 0
