#!/bin/sh
#
# setup lirc


# read the config
if test -f /etc/remote; then
  . /etc/remote
  cp -f /etc/lirc/lircrc_$REMOTE /etc/lircrc
  cp -f /etc/lirc/lircd_$REMOTE /etc/lircd
  cp -f /etc/lirc/lircd_$REMOTE.conf /etc/lircd.conf
fi
. /etc/lircd

# insert needed modules
IFS='|'
for module in $LIRC_MODULES; do
  module_name=`echo $module | cut -d" " -f1`
  module_options=`echo $module | cut -d" " -f2-`
  insmod $module_name $module_options >/dev/null 2>&1
done

# start lircd
lircd --driver=$LIRC_DRIVER --device=$LIRC_DEVICE

exit 0
