#!/bin/sh
#
# setup lirc

echo "### Starting LIRC daemon ###"

# read the config
if test -f /etc/remote; then
  . /etc/remote
  cp -f /etc/lirc/lircrc_$REMOTE /etc/lircrc
  cp -f /etc/lirc/lircd_$RECEIVER /etc/lircd
  cp -f /etc/lirc/lircd_$REMOTE.conf /etc/lircd.conf
fi
. /etc/lircd

# insert needed modules
IFS='|'
for module in $LIRC_MODULES; do
  eval "modprobe $module" >/dev/null 2>&1
done

# start lircd
lircd --driver=$LIRC_DRIVER --device=$LIRC_DEVICE

exit 0
