#!/bin/sh
#
# configure and launch mplayer

# include audio configuration file
. /etc/audio

# include tvout configuration file
. /etc/tvout

# default directory
cd /mnt

# remove DVD from the menu if no dvd drive available
test -e /dev/dvd || sed -i 's/.*DVD.*//' /etc/mplayer/menu.conf

# remove image viewer from the menu if fbi is not present
test -x /usr/bin/fbi || sed -i 's/.*set_menu\ view_img.*//' /etc/mplayer/menu.conf

# add partitions free space in menu
for i in `mount | sed -n 's%/dev/\([sh]d[a-z][0-9]\).*%\1%p'`; do
  MENU_DF="$MENU_DF <e name=\"$i\"/>"
done
[ -n "$MENU_DF" ] && sed -i "s%name=\"ip\"/>%name=\"ip\"/> $MENU_DF%" /etc/mplayer/menu.conf

# set double to no for nvidia, sis and Kyro cards and VMWare
for i in 'Class 0300:.*10de:' 'Class 0300:.*1039:' 'Class 0300:.*104a:0010' 'Class 0300:.*15ad:'; do
  if grep "$i" /proc/pci >/dev/null 2>&1; then
    # except if we want to try nvidia vidix
    if [ "$i" = 'Class 0300:.*10de:' -a ! -f /etc/mplayer/no_nvidia_vidix ]; then
      if [ -n "`grep '^vf=' /etc/mplayer/mplayer.conf`" ]; then
        sed -i 's/^\(vf=.*\)/\1,format=yuy2/' /etc/mplayer/mplayer.conf
      else
        echo 'vf=format=yuy2' >> /etc/mplayer/mplayer.conf
      fi
    else
      sed -i 's/^vo=.*/vo=vesa/' /etc/mplayer/mplayer.conf
      sed -i 's/^double=.*/double=no/' /etc/mplayer/mplayer.conf
      if [ -n "`grep '^vf=' /etc/mplayer/mplayer.conf`" ]; then
        sed -i 's/^\(vf=.*\)/\1,expand=-1:-1:-1:-1:1/' /etc/mplayer/mplayer.conf
      else
        echo 'vf=expand=-1:-1:-1:-1:1' >> /etc/mplayer/mplayer.conf
      fi
    fi
  fi
done

# force VBE 3.0 extensions for Intel i845G(L)/i855GM/i865G and 3Dfx cards
for i in 'Class 0300:.*8086:2562' 'Class 0300:.*8086:3582' 'Class 0300:.*8086:2572' 'Class 0300:.*121a:'; do
  if grep "$i" /proc/pci >/dev/null 2>&1; then
    sed -i 's/^vo=.*/vo=vesa:vbe3/' /etc/mplayer/mplayer.conf
  fi
done

# set ao to SPDIF when specified
if test "$SPDIF" = yes; then
  sed -i 's/^ao=.*/ao=alsa:device=spdif/' /etc/mplayer/mplayer.conf
fi

# set the tvout aspect
echo "monitoraspect=$TVOUT_ASPECT" >> /etc/mplayer/mplayer.conf

# set ao, vo and vf for DXR3/Hollywood+ cards and upload microcode.
if test -n "`grep 'Class 0480:.*1105:8300' /proc/pci 2>/dev/null`"; then
  sed -i 's/^vo=.*/vo=dxr3:sync:norm=0/' /etc/mplayer/mplayer.conf
  sed -i 's/^ao=.*/ao=oss:\/dev\/em8300_ma-0/' /etc/mplayer/mplayer.conf
  if [ -n "`grep '^vf=' /etc/mplayer/mplayer.conf`" ]; then
    sed -i 's/^\(vf=.*\)/\1,expand=-1:-1:-1:-1:1/' /etc/mplayer/mplayer.conf
  else
    echo 'vf=expand=-1:-1:-1:-1:1' >> /etc/mplayer/mplayer.conf
  fi
  sed -i "s%play_dvd.*%quit 167\"/>%" /etc/mplayer/menu.conf
  em8300setup -p -a -o -f /usr/share/em8300.uc >/dev/null 2>&1
  echo '' > /var/use_dxr3

  # TVOut standard (default is PAL)
  if [ "$TVOUT_STANDARD" = "ntsc" ]; then
    em8300setup -n >/dev/null 2>&1
  fi

  # set display to WideScreen format (default is 4:3)
  if [ "$TVOUT_ASPECT" = "16:9" ]; then
    em8300setup -w >/dev/null 2>&1
  fi

  # use SPDIF output ?
  if test "$SPDIF" = yes; then
    em8300setup -d >/dev/null 2>&1
  fi
fi

# create the mplayer control pipe for external programs
mkfifo /var/mp_control

# start the autolaunching script
if test -e /usr/bin/autolaunch; then
  sh /usr/bin/autolaunch > /var/mp_control &
fi

# start the file copy daemon
/usr/bin/cpd &

# give a shell in debug mode
if test "$DEBUG" = yes; then
  sed -i 's%ok=\"halt\"/>%ok=\"halt\"/>  <e name=\"Console\" ok=\"set_menu console\"/>%' /etc/mplayer/menu.conf
  /bin/sh
fi

# disable console blanking and cursor blinking
echo -e "\033[9;0]"
echo -e "\033[?25l"

# start mplayer with gdb when built with debugging options
if test -x /usr/bin/gdb; then
  echo "r /usr/share/mplayer/background.avi -loop 0" > /gdb_cmd
  gdb -x /gdb_cmd /usr/bin/mplayer
else
  echo "0" > /tmp/mp_result
# start mplayer or fbi and keep then launched
  while true; do
    if [ -n "`pidof lircd`" ]; then
      irpty /etc/lircrc -- mp_wrapper
    else
      mp_wrapper
    fi
    test `cat /tmp/mp_result` -eq 165 -a -x /usr/bin/fbi && fbi_wrapper
    test `cat /tmp/mp_result` -eq 166 && break
    test `cat /tmp/mp_result` -eq 167 && mplayer dvd://1 > /dev/null 2>&1
  done
fi

exit 0
