#!/bin/sh
#
# setup the network


# get options
test -f /etc/network || exit 1
. /etc/network
test -z "$HOST" && HOST=0.0.0.0
WIFI=`iwconfig 2>&1 | grep '^[^\ ]' | grep -v "no wireless extensions" | cut -f1 -d' ' | head -n 1`
ETH=`iwconfig 2>&1 | grep '^[^\ ]'  | grep -v '^lo' | grep "no wireless extensions" | cut -f1 -d' ' | head -n 1`

# select device
if test $PHY_TYPE = wifi -o $PHY_TYPE = auto; then
  DEV=$WIFI
  if test -n "$DEV"; then
    test -n "$WIFI_MODE" && iwconfig "$DEV" mode $WIFI_MODE
    test -n "$WIFI_ESSID" && iwconfig "$DEV" essid $WIFI_ESSID
    test -n "$WIFI_WEP" && iwconfig "$DEV" key $WIFI_WEP
  fi
fi
if test $PHY_TYPE = ethernet -o $PHY_TYPE = auto -a -z "$DEV"; then
  DEV=$ETH
fi
test -n "$DEV" || exit 1

# bring interface up
if ifconfig $DEV $HOST >/dev/null 2>&1; then
  if test $HOST = 0.0.0.0; then
    udhcpc -H geexbox -n >/dev/null 2>&1 && NET=yes
    test "$NET" = yes || ifconfig $DEV 192.168.0.54 && NET=yes
  else
    test -n "$GATEWAY" && route add default gw $GATEWAY
    NET=yes
  fi
fi
test "$NET" = yes || exit 1

# load ftp server
if test -f /etc/bftpd.conf; then
  bftpd -d -c /etc/bftpd.conf
fi

IFS='
'

# mount nfs shares
if test -f /etc/nfs; then
  for MOUNTS in `grep -v "^#" /etc/nfs | grep -v "^$"`; do
    SRV=`echo $MOUNTS | sed 's/[ ]*\([^ ]*\)[ ]*.*/\1/'`
    DIR=`echo $MOUNTS | sed 's/[ ]*[^ ]*[ ]*\([^ ]*\)/\1/'`
    mkdir -p /mnt/nfs/$DIR
    mount -t nfs -o ro,nolock,nfsvers=2 $SRV /mnt/nfs/$DIR >/dev/null 2>&1
  done
fi

# mount samba shares
if test -x /usr/bin/smbmount; then
  OPT="-N"
  test -n "$SMB_USER" && OPT="-U$SMB_USER%$SMB_PWD"
  for i in `smbtree $OPT | sed -n 's/.*\\\\\\\\\(.*\)\\\\\([^$]*\)\ \ .*/\1\/\2/p' | sed 's/\ *$//'`; do
    mkdir -p "/mnt/shares/$i"
    smbmount "//$i" "/mnt/shares/$i" -o ro,username=$SMB_USER,passwd=$SMB_PWD >/dev/null 2>&1 || rmdir -p "/mnt/shares/$i" >/dev/null 2>&1
  done
fi

exit 0
