#!/bin/sh
#
# setup the tvout


test -f /etc/tvsettings || exit 1

. /etc/tvsettings

atitvout $TVSTANDARD auto >/dev/null 2>&1
test "`atitvout active 2>/dev/null | sed -n 's/TV.*/TV/p'`" = "TV" && echo "" > /var/tvout

# There is no possibility of tv cable autodetection with nvtv so
# tvout is not enabled automatically. Uncomment the following lines
# to have nvtv tvout enabled at boot.
#nvtv $NVTV_ON >/dev/null 2>&1
#echo "" > /var/tvout

# The same applies to S3 cards for which you need to uncomment
# the following lines.
#s3switch -q tv $TVSTANDARD >/dev/null 2>&1
#echo "" > /var/tvout

exit 0
