#!/bin/sh
#
# umount all mounted disks


# umount samba shares
for DIR in /mnt/share/*/*; do
  test -d "$DIR" && umount "$DIR" >/dev/null 2>&1 && rmdir -p "$DIR"
done

# when started with make exec, umount partitions
if test -f /EXEC; then
  for DIR in /mnt/*; do
    test -d "$DIR" && umount "$DIR" >/dev/null 2>&1
  done
  umount /proc
fi

exit 0
