#!/bin/sh

. config/options

[ "$TARGET_ISO" = yes ] && $SCRIPTS/iso
[ "$TARGET_FLAT" = yes ] && $SCRIPTS/flat
[ "$TARGET_PXE" = yes ] && $SCRIPTS/pxe
[ "$TARGET_VMX" = yes ] && $SCRIPTS/vmx build

exit 0
