#!/bin/sh

. config/options

[ "$TARGET_ISO" = yes ] && $SCRIPTS/iso
[ "$TARGET_FLAT" = yes ] && $SCRIPTS/flat
[ "$TARGET_PXE" = yes ] && $SCRIPTS/pxe
[ "$TARGET_VMX" = yes ] && $SCRIPTS/vmx build
[ "$TARGET_EXT2FS" = yes ] && $SCRIPTS/ext2fs
[ "$TARGET_INITRAMFS" = yes ] && $SCRIPTS/initramfs
[ "$TARGET_SNOWBALL_EMMC" = yes ] && $SCRIPTS/mksnowball
[ "$TARGET_TARBALL" = yes ] && $SCRIPTS/tarball
[ "$TARGET_SDCARD_GEN" = yes ] && $SCRIPTS/sdcard-gen

[ "$PACKAGE_REPO" = yes ] && $SCRIPTS/index

echo ""
echo ""
echo "#########################################################################"
echo "##"
echo "## Build completed successfully !!"
echo "##  + Flavour:      $DISTRONAME"
echo "##  + Version:      $DISTRO_VERSION"
echo "##  + Architecture: $TARGET_ARCH"
echo "##  + Platform:     $TARGET_PLATFORM"
echo "##  + Board:        $TARGET_MACHINE"
echo "##"
echo "## Binary Location: $BINROOT"
echo "##"
echo "#########################################################################"
echo ""
echo ""


# Test if doozer-agent is here
if [ -n "$DOOZER_CONCURRENCY_MAKE_LEVEL" ] ; then
  if [ "$TARGET_ARCH" = "i386" -o "$TARGET_ARCH" = "x86_64" ] ; then
    name=$(basename $ISO)
    val="iso:application/octet-stream:$name"
    echo "doozer-artifact:$BINROOT:$val"
  fi
  if [ "$TARGET_ARCH" = "arm" ] ; then
    name=$(basename $XZ_NAME)
    val="xz:application/x-xz:$name"
    echo "doozer-artifact:$BINROOT:$val"
    echo "doozer-artifact:$BINROOT:txt:application/octet-stream:make-sdcard"
  fi
fi

exit 0
