#!/bin/sh

. config/options

[ "$TARGET_ISO" = yes ] && $SCRIPTS/iso
[ "$TARGET_FLAT" = yes ] && $SCRIPTS/flat
[ "$TARGET_PXE" = yes ] && $SCRIPTS/pxe
[ "$TARGET_VMX" = yes ] && $SCRIPTS/vmx build
[ "$TARGET_EXT2FS" = yes ] && $SCRIPTS/ext2fs

$SCRIPTS/index

echo ""
echo ""
echo "#########################################################################"
echo "##"
echo "## Build completed successfully !!"
echo "##  + Flavour:      $DISTRONAME"
echo "##  + Version:      $DISTRO_VERSION"
echo "##  + Architecture: $TARGET_ARCH"
echo "##  + Platform:     $TARGET_PLATFORM"
echo "##  + Board:        $TARGET_MACHINE"
echo "##"
echo "## Binary Location: $BINROOT"
echo "##"
echo "#########################################################################"
echo ""
echo ""

exit 0
