#!/bin/sh

. config/options

$SCRIPTS/build bootsplash

cd $BUILD/$1*

. ./config

for r in `ls bootsplash-*.cfg | sed "s%bootsplash-\(.*\).cfg%\\1%g"`; do
  $ROOT/$BUILD/bootsplash*/Utilities/splash -s -f bootsplash-$r.cfg > bootsplash-$r.dat
done

rm -f bootsplash-*.cfg bootsplash-*.jpg bootsplash-*.jpeg
