#!/bin/sh

. config/options

$SCRIPTS/build bootsplash

cd $BUILD/$1*

. ./config
[ -z "$RESOLUTIONS" ] && RESOLUTIONS=800x600

for r in $RESOLUTIONS; do
  $ROOT/$BUILD/bootsplash*/Utilities/splash -s -f bootsplash-$r.cfg > bootsplash-$r.dat
done

rm -f bootsplash-*.cfg bootsplash-*.jpg bootsplash-*.jpeg
