#!/bin/sh

. config/options

if [ ! -f $ISO-$LANG.iso ]; then
  $SCRIPTS/iso || exit 1
fi

if [ "$BLANK" = "yes" ]; then
  CDRECORD_OPTS="blank=fast $CDRECORD_OPTS"
fi

cdrecord dev=$BURNER $CDRECORD_OPTS -eject $ISO-$LANG.iso
