#!/bin/sh

. config/options

$SCRIPTS/checkdeps burn

[ ! -f $ISO-$LANG.iso ] && $SCRIPTS/iso

if [ "$BLANK" = "yes" ]; then
  CDRECORD_OPTS="blank=fast $CDRECORD_OPTS"
fi

cdrecord dev=$BURNER $CDRECORD_OPTS -eject $ISO-$LANG.iso
