#!/bin/sh

. config/options

RESULT_FILE="$ROOT/$BUILD_NOARCH/checkurl-result-$(date +%Y%M%d%H%M).txt"
NB_FAILED=0
NB_URL_OK=0
NB_NO_URL=0

for i in $PACKAGES/* ; do
  j=${i#$PACKAGES/}
  get_meta $j
  if [ -n "$PKG_URL" ]; then
    echo "###"
    echo "Checking for $j : $PKG_URL"
    if wget --no-check-certificate --passive-ftp --spider -nv -q $PKG_URL ; then
      echo "OK"
      NB_URL_OK=$(($NB_URL_OK+1))
    elif wget -nv -q $PKG_URL -O /dev/null; then
      echo "OK"
      NB_URL_OK=$(($NB_URL_OK+1))
    else
      echo "Failed"
      mkdir -p $ROOT/$BUILD_NOARCH
      echo "$j : $PKG_URL failed" >> $RESULT_FILE
      NB_FAILED=$(($NB_FAILED+1))
    fi
  else
    NB_NO_URL=$(($NB_NO_URL+1))
  fi
done

echo "###########################################################################"
echo "##                                RESULTS                                ##"
if [ -f $RESULT_FILE ] ; then
  echo "## Found $NB_FAILED invalid url(s), please check $RESULT_FILE  ##"
else
  echo "##                        Good day, no url to fix ;)                      ##"
fi
echo "##                        $NB_URL_OK urls are valid                             ##"
echo "##                         $NB_NO_URL packages without url                       ##"
echo "###########################################################################"
