#!/bin/sh

. config/path

deps="gcc make patch nasm bzip2 gzip mke2fs mkfs.vfat wget mkisofs mkzftree cdrecord perl"
deps_pkg="gcc make patch nasm bzip2 gzip e2fsprogs dosfstools wget mkisofs mkisofs cdrecord perl"
files="/usr/include/stdio.h"
files_pkg="libc6-dev"

if [ -n "`gcc -dumpversion | grep '^3.3'`" ]; then
  echo "**** GCC 3.3 is currently not supported ****"
  exit 1
fi

deps=($deps)
deps_pkg=($deps_pkg)
nb_deps=${#deps[*]}
for ((i=0; i<$nb_deps; i++)); do
  [ -z "`which ${deps[$i]}`" ] && need="$need ${deps[$i]}" && need_pkg="$need_pkg ${deps_pkg[$i]}"
done

files=($files)
files_pkg=($files_pkg)
nb_files=${#files[*]}
for ((i=0; i<$nb_files; i++)); do
  [ ! -f ${files[$i]} ] && need="$need ${files_pkg[$i]}" && need_pkg="$need_pkg ${files_pkg[$i]}"
done

if [ -n "$need" ]; then
  echo "**** Your system lake the following tools to build the GeeXboX ****"
  echo $need
  if [ -f /etc/debian_version -a -n "`which apt-get`" ]; then
    echo "**** You seem to use a debian system ****"
    if [ $UID -ne 0 ]; then
      echo "**** I could install those packages but you need to be root for this ****"
      exit 1
    else
      read -p "would you like to apt-get install the needed tools ? (y/n) " ans
      [ "$ans" = "y" ] && apt-get install $need_pkg || exit 1
    fi
  else
    echo "********"
    exit 1
  fi
fi


need=""
need_pkg=""
for ((i=0; i<$nb_deps; i++)); do
  [ -z "`which ${deps[$i]}`" ] && need="$need ${deps[$i]}" && need_pkg="$need_pkg ${deps_pkg[$i]}"
done

for ((i=0; i<$nb_files; i++)); do
  [ ! -f "${files[$i]}" ] && need="$need ${files_pkg[$i]}" && need_pkg="$need_pkg ${files_pkg[$i]}"
done

if [ -n "$need" ]; then
  if [ "$need" = " mkzftree" ]; then
    echo "**** mkzftree was not installed correctly."
    echo "**** It is not included in debian woody."
    echo "**** You will need for example a sarge version of mkisofs."
  else
    echo "**** The following packages were not installed correctly ****"
    echo $need_pkg
    echo "********"
  fi
  exit 1
fi

exit 0
