#!/bin/sh

. config/options

deps=
deps_pkg=
files=
files_pkg=

case $1 in
  get)
    deps="wget"
    deps_pkg="wget"
    ;;
  build)
    deps="gcc g++ sed patch touch nasm tar bzip2 gzip perl flex"
    deps_pkg="gcc g++ sed patch fileutils nasm tar bzip2 gzip perl flex"
    files="/usr/include/stdio.h"
    files_pkg="libc6-dev"
    ;;
  burn)
    deps="cdrecord"
    deps_pkg="cdrecord"
    ;;
  iso)
    deps="mkisofs mkzftree"
    if [ -f /etc/debian_version -a -n "`which apt-get 2>/dev/null`" ]; then
      deps_pkg="mkisofs mkisofs"
    else
      deps_pkg="mkisofs zisofs-tools"
    fi
    ;;
esac

getarg() {
  eval echo \${$(($1+2))}
}

i=0
while dep=`getarg $i $deps` && [ -n "$dep" ]; do
  [ -z "`which $dep 2>/dev/null`" ] && need="$need $dep" && need_pkg="$need_pkg `getarg $i $deps_pkg`"
  i=$(($i+1))
done

i=0
while file=`getarg $i $files` && [ -n "$file" ]; do
  [ ! -f $file ] && need="$need $file" && need_pkg="$need_pkg `getarg $i $files_pkg`"
  i=$(($i+1))
done

if [ -n "$need" ]; then
  echo "**** Your system lacks the following tools needed to $1 GeeXboX ****"
  echo $need
  if [ -f /etc/debian_version -a -n "`which apt-get 2>/dev/null`" ]; then
    echo "**** You seem to use a debian system ****"
    if [ $UID -ne 0 ]; then
      echo "**** I could install those packages but you need to be root for this ****"
      exit 1
    else
      read -p "would you like to apt-get install the needed tools ? (y/n) " ans
      [ "$ans" = "y" ] && apt-get install $need_pkg
    fi
  elif [ -f /etc/mandrake-release -a -n "`which urpmi 2>/dev/null`" ]; then
    echo "**** You seem to use a mandrake system ****"
    if [ $UID -ne 0 ]; then
      echo "**** I could install those packages but you need to be root for this ****"
      exit 1
    else
      read -p "would you like to urpmi the needed tools ? (y/n) " ans
      [ "$ans" = "y" ] && urpmi $need_pkg
    fi
  else
    echo "********"
    exit 1
  fi
fi


need=""
need_pkg=""

i=0
while dep=`getarg $i $deps` && [ -n "$dep" ]; do
  [ -z "`which $dep 2>/dev/null`" ] && need="$need $dep" && need_pkg="$need_pkg `getarg $i $deps_pkg`"
  i=$(($i+1))
done

i=0
while file=`getarg $i $files` && [ -n "$file" ]; do
  [ ! -f $file ] && need="$need $file" && need_pkg="$need_pkg `getarg $i $files_pkg`"
  i=$(($i+1))
done

if [ -n "$need" ]; then
  if [ "$need" = " mkzftree" ]; then
    echo "**** mkzftree was not installed correctly."
    echo "**** It is not included in debian woody."
    echo "**** You will need for example a sarge version of mkisofs."
  else
    echo "**** The following packages were not installed correctly ****"
    echo $need_pkg
    echo "********"
  fi
  exit 1
fi
