#!/bin/sh

. config/options

clean ()
{
  printf "%${INDENT}c CLEAN    $1\n" >&$SILENT_OUT
  export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

  if [ "$CLEAN_SOURCES" = true ]; then
    if [ -f $PACKAGE_URL ]; then
      for i in `ls $SOURCES/$1 2>/dev/null`; do
        grep -q $i $PACKAGE_URL || rm -rf $SOURCES/$1/$i
      done
    fi
    return
  fi

  if [ "$FULL" = true ]; then
    rm -rf $BUILD_BASE*/$STAMPS_NOARCH/$1*
    rm -rf $BUILD_BASE*/$1*
    rm -rf $STAMPS_NOARCH/$1
    rm -rf $SOURCES/$1
  else
    [ "$1" != toolchain ] && rm -rf $BUILD/$1* || true
    rm -f $STAMPS/$1*/unpack
    rm -f $STAMPS/$1*/build
    $SCRIPTS/unpackage $1
    [ "$1" != opkg-host ] && $SCRIPTS/unpackagedev $1 || true
  fi

  unset INDENT
}

if [ "$1" = "--full" ]; then
  FULL=true
  shift
elif [ "$1" = "--sources" ]; then
  CLEAN_SOURCES=true
  shift
fi

if [ -z "$1" ]; then
  for i in $PACKAGES/*; do clean ${i#$PACKAGES/}; done
  $SCRIPTS/unpackagedev opkg-host
  rm -rf $BUILD/toolchain
  rm -rf $BUILD/iso
  rm -rf $BUILD/rootfs
  rm -rf $BUILD/packages
  rm -rf $BUILD/devpackages
  rm -rf $BUILD/initrd
  [ "$FULL" = true ] && rm -rf $CCACHE_DIR
else
  clean $1
fi

exit 0
