#!/bin/sh -e

DEVICE="$1"
ROOTFS="$2"

if [ ! -b "$DEVICE" ] || [ ! -f "$ROOTFS" -a ! -d "$ROOTFS" ]; then
  echo "Usage: $0 <device> <rootfs|rootfs-archive>"
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this program as root."
  exit 1
fi

if [ -z "$(which parted)" ]; then
  echo "Please install parted."
  exit 2
fi

echo "\nI'm about to overwrite ${DEVICE}. All existing data will be lost."
until [ "$REPLY" = y -o "$REPLY" = yes ] || [ "$REPLY" = n -o "$REPLY" = no ]; do
  read -p "Do you want to continue? " REPLY
done
[ "$REPLY" = n -o "$REPLY" = no ] && exit

grep -q $DEVICE /proc/mounts && grep $DEVICE /proc/mounts | cut -f2 -d\ | xargs umount

echo "\n#### Creating partion..."
parted -s $DEVICE mktable msdos
parted -s --align=opt $DEVICE mkpart primary 0% 100%
parted -s $DEVICE print

echo "\n#### Creating file system..."
echo $DEVICE | grep -q mmc && OPT=p
root_part=${DEVICE}${OPT}1
mkfs.ext4 -L GEEXBOX $root_part

mountdir=`mktemp -d`
mount $root_part $mountdir

echo "\n#### Copying files..."
if [ -d "$ROOTFS" ]; then
  cp -PR $ROOTFS/* $mountdir
else
  tar --no-same-owner -xjf $ROOTFS -C $mountdir
fi
df -h $root_part

echo "\n#### Umount..."
umount $mountdir
rmdir $mountdir

echo "\n#### Sync..."
sync
echo "\n#### Done"
