#!/bin/sh

. config/options

if [ -z "$3" ]; then
  echo "usage: $0 package_name file_pattern target_dir"
  exit 1
fi

get_meta $1

[ ! -f $PACKAGE_URL -a -z "$PKG_URL" ] && exit 1

[ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1

if [ -n "$PKG_URL_PROTO" ]; then
    REPO_BASENAME=$PKG_NAME-$PKG_VERSION
    FILES=$REPO_BASENAME.tar.bz2
else
  [ -f $PACKAGE_URL ] && \
    FILES=`sed 's%.*/\(.*\)\$%\1%' $PACKAGE_URL`

  [ -n "$PKG_URL" ] && \
    for url in $PKG_URL; do
      FILES="$FILES `echo $url | sed 's%.*/\(.*\)\$%\1%'`"
    done
fi

for s in $FILES; do
  case $s in
  $2)
    f="$SOURCES/$1/$s"
    if [ ! -f $f ]; then
      echo "error: File $s doesn't exist in package $1 sources directory"
      echo "have you called scripts/extract before scripts/get ?"
      exit 1
    fi
    case $s in
      *.tar)
        tar xf $f -C $3
        ;;
      *.tar.bz2 | *.tbz)
        tar xjf $f -C $3
        ;;
      *.tar.gz | *.tgz)
        tar xzf $f -C $3
        ;;
      *.diff | *.patch)
        cat $f | patch -d $3 -p1
        ;;
      *.diff.bz2 | *.patch.bz2 | patch-*.bz2)
        bzcat $f | patch -d $3 -p1
        ;;
      *.diff.gz | *.patch.gz | patch-*.gz)
        zcat $f | patch -d $3 -p1
        ;;
      *)
        cp -pPR $f $3
        ;;
    esac
    ;;
  esac
done
