#!/bin/sh

. config/options

if [ -z "$3" ]; then
  echo "usage: $0 package_name file_pattern target_dir"
  exit 1
fi

[ ! -d "$SOURCES/$1" -o ! -f $PACKAGES/$1/url -o ! -d "$3" ] && exit 1

for f in `ls $SOURCES/$1/$2`; do
    case $f in
      *.tar)
        tar xf $f -C $3
        ;;
      *.tar.bz2 | *.tbz)
        tar xjf $f -C $3
        ;;
      *.tar.gz | *.tgz)
        tar xzf $f -C $3
        ;;
      *.diff | *.patch)
        cat $f | patch -d $3 -p1
        ;;
      *.diff.bz2 | *.patch.bz2)
        bzcat $f | patch -d $3 -p1
        ;;
      *.diff.gz | *.patch.gz)
        zcat $f | patch -d $3 -p1
        ;;
      *)
        cp -pPR $f $3
        ;;
    esac
done
