#!/bin/sh

. config/options

# Avoid infinite loop
[ "$*" == "$BUILD/configtools" ] && exit 0

$SCRIPTS/unpack configtools || exit 1

for i in $@; do
  [ -f "$i/config.guess" ] && cp -f $BUILD/configtools/config.guess $i || exit 1
  [ -f "$i/config.sub" ]   && cp -f $BUILD/configtools/config.sub   $i || exit 1
done
