#!/bin/sh

. config/options

$SCRIPTS/checkdeps build

rm -rf $FLAT_NAME
mkdir -p $FLAT_NAME
export INSTALL=$FLAT_NAME

$SCRIPTS/install linux image
[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs
cp -PR $ROOTFS/* $FLAT_NAME
