#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

rm -rf $FLAT_NAME
mkdir -p $FLAT_NAME

[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs
cp -PR $ROOTFS/* $FLAT_NAME

. $CONFIG_MACHINE/meta

if [ -n "$MACHINE_XLOADER_CONFIG" ]; then
  $SCRIPTS/installdev x-loader
  mkdir -p $FLAT_NAME/boot
  cp -P $ROOT/$TOOLCHAIN/share/x-loader/* $FLAT_NAME/boot
fi

if [ -n "$MACHINE_UBOOT_CONFIG" ]; then
  $SCRIPTS/installdev u-boot
  mkdir -p $FLAT_NAME/boot
  cp -P $ROOT/$TOOLCHAIN/share/u-boot/* $FLAT_NAME/boot
fi

exit 0
