#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

export INSTALL=$GENERATOR_NAME/iso/$DISTRONAME_UC
export NOROOTFS=0
rm -rf $GENERATOR_NAME
$SCRIPTS/image generator

export INSTALL=$GENERATOR_NAME
$SCRIPTS/install generator
mkdir -p $GENERATOR_NAME/$DOCS
cp -r $DOCS/* $GENERATOR_NAME/$DOCS/
cp $CONFIG/sort $GENERATOR_NAME/sort
cp $CONFIG/maps $GENERATOR_NAME/maps
cp AUTHORS $GENERATOR_NAME/AUTHORS
cp COPYING $GENERATOR_NAME/COPYING
echo $DISTRO_VERSION-custom > $GENERATOR_NAME/VERSION
cat $PACKAGES/*/config/packages.ini > $GENERATOR_NAME/packages.ini
tar cf - $GENERATOR_NAME | gzip -f > $GENERATOR_NAME.tar.gz
rm -rf $GENERATOR_NAME
