#!/bin/sh

. config/path
. $CONFIG/options

$SCRIPTS/checkdeps || exit 1

export INSTALL=$GENERATOR_NAME/iso/GEEXBOX
rm -rf $GENERATOR_NAME

mkdir -p $INSTALL/sbin
cp $CONFIG/init $INSTALL/sbin

$SCRIPTS/install linux image generator || exit 1
$SCRIPTS/install linux modules generator || exit 1
$SCRIPTS/install initrd generator || exit 1
$SCRIPTS/install syslinux generator || exit 1
$SCRIPTS/install eject generator || exit 1
$SCRIPTS/install alsa generator || exit 1
$SCRIPTS/install tvout generator || exit 1
$SCRIPTS/install setcd generator || exit 1
$SCRIPTS/install MPlayer generator || exit 1
$SCRIPTS/install network generator || exit 1
$SCRIPTS/install installator generator || exit 1

export INSTALL=$GENERATOR_NAME
$SCRIPTS/install generator-win32 generator || exit 1
export INSTALL=$GENERATOR_NAME/win32
mkdir -p $INSTALL
$SCRIPTS/install mkisofs-win32 generator || exit 1
cp -r $GENERATOR/* $GENERATOR_NAME
cp -r $DOCS $GENERATOR_NAME
cp COPYING $GENERATOR_NAME/COPYING
echo $GEEXBOX_VERSION-custom > $GENERATOR_NAME/VERSION
tar czf $GENERATOR_NAME.tar.gz $GENERATOR_NAME
rm -rf $GENERATOR_NAME
