#!/bin/sh

. config/options

if [ "$2" != boot ]; then
  mkdir -p $INSTALL/sbin
  mkdir -p $INSTALL/etc/init.d
  mkdir -p $INSTALL/codecs
  cp $CONFIG/init $INSTALL/sbin
  cp $CONFIG/init.d/* $INSTALL/etc/init.d/
  cp $CONFIG/lang.conf $INSTALL/etc
  cp $CONFIG/lang.funcs $INSTALL/etc
  cp $CONFIG/file_ext $INSTALL/etc
  cp $CONFIG/list_ext $INSTALL/etc
  cp $CONFIG/audio $INSTALL/etc

  $SCRIPTS/install linux modules $1 || exit 1
  $SCRIPTS/install eject $1 || exit 1
  $SCRIPTS/install alsa $1 || exit 1
  $SCRIPTS/install tvout $1 || exit 1
  $SCRIPTS/install setcd $1 || exit 1
  $SCRIPTS/install zlib || exit 1
  $SCRIPTS/install MPlayer $1 || exit 1
  $SCRIPTS/install installator $1 || exit 1
  if [ "$NETWORK" = yes ]; then $SCRIPTS/install network $1 || exit 1; fi
  if [ "$DXR3" = yes ]; then $SCRIPTS/install em8300 $1 || exit 1; fi
  if [ "$VIEW_IMG" = yes ]; then $SCRIPTS/install fbi $1 || exit 1; fi
  if [ "$DEBUG" = yes ]; then $SCRIPTS/install gdb $1 || exit 1; fi
  if [ "$EXTRACODECS" = yes ]; then $SCRIPTS/install essential $1 || exit 1; fi

  VER=`ls $INSTALL/lib/modules`
  $BUILD/module-init-tool*/depmod -b $INSTALL -v $VER > /dev/null || exit 1
  for i in `ls $INSTALL/lib/modules/*/modules.* | grep -v modules.dep`; do
    rm -f $i
  done

  tar cj -C $INSTALL -f $INSTALL/bin.tar.bz2 lib usr/bin usr/lib
  rm -rf $INSTALL/lib $INSTALL/usr/bin $INSTALL/usr/lib
fi

if [ "$2" = boot -o "$2" = full ]; then
  $SCRIPTS/install linux image $1 || exit 1
  $SCRIPTS/install initrd $1 || exit 1
  $SCRIPTS/install syslinux $1 || exit 1
fi
