#!/bin/sh

. config/options

if [ "$2" != boot ]; then
  mkdir -p $INSTALL/sbin
  mkdir -p $INSTALL/etc/init.d
  mkdir -p $INSTALL/codecs
  cp $CONFIG/init $INSTALL/sbin
  cp $PACKAGES/*/init.d/* $INSTALL/etc/init.d/
  cp $CONFIG/file_ext $INSTALL/etc
  cp $CONFIG/list_ext $INSTALL/etc

  $SCRIPTS/install linux modules $1
  $SCRIPTS/install alsa $1
  $SCRIPTS/install tvout $1
  $SCRIPTS/install pciutils $1
  $SCRIPTS/install MPlayer $1
  $SCRIPTS/install installator $1
  $SCRIPTS/install i18n $1
  $SCRIPTS/install webgui $1
  $SCRIPTS/install theme $1
  $SCRIPTS/install cpufreqd $1
  [ "$NETWORK" = yes ] && $SCRIPTS/install network $1
  [ "$RADIO" = yes ] && $SCRIPTS/install fmio $1
  [ "$DXR3" = yes ] && $SCRIPTS/install em8300 $1
  [ "$VIEW_IMG" = yes ] && $SCRIPTS/install fbi $1
  [ "$DEBUG" = yes ] && $SCRIPTS/install gdb $1
  [ "$EXTRACODECS" = yes ] && $SCRIPTS/install essential $1

  VER=`ls $INSTALL/lib/modules`
  $BUILD/module-init-tool*/depmod -b $INSTALL -v $VER > /dev/null
  for i in `ls $INSTALL/lib/modules/*/modules.* | grep -v modules.dep`; do
    rm -f $i
  done

  tar cj -C $INSTALL -f $INSTALL/bin.tar.bz2 lib usr/bin usr/lib
  rm -rf $INSTALL/lib $INSTALL/usr/bin $INSTALL/usr/lib
fi

if [ "$2" = boot -o "$2" = full ]; then
  $SCRIPTS/install linux image $1
  $SCRIPTS/install initrd $1
  $SCRIPTS/install syslinux $1
  $SCRIPTS/install yaboot $1
fi
