#!/bin/sh

. config/options

NOGET="gdb termcap"

if [ -z "$1" ]; then
  for i in $PACKAGES/*; do
    GET=yes
    for j in $NOGET; do
      [ ${i##*/} = $j ] && GET=no break
    done
    if [ $GET = yes ]; then
      $SCRIPTS/get ${i#$PACKAGES} || exit 1
    fi
  done
  exit 0
fi

mkdir -p .stamps/$1

if [ -f $PACKAGES/$1/url ]; then
  if [ -f .stamps/$1/get ]; then
    exit 0
  fi

  printf "%${INDENT}c GET      $1\n" >&$SILENT_OUT
  export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

  [ "$VERBOSE" != yes ] && WGET_OPT=-q

  mkdir -p $SOURCES/$1
  URLS=`cat $PACKAGES/$1/url`
  for i in ${URLS//GEEXBOX_SRCS/${GEEXBOX_SRCS}}; do
    wget --passive-ftp -c $WGET_OPT -P $SOURCES/$1 $i || exit 1
  done

  touch .stamps/$1/get
  rm -f .stamps/$1/unpack
  rm -f .stamps/$1/build
  rm -f .stamps/$1/install
fi
