#!/bin/sh

. config/options

NOGET="gdb termcap"

if [ -z "$1" ]; then
  for i in $PACKAGES/*; do
    GET=yes
    for j in $NOGET; do
      [ ${i##*/} = $j ] && GET=no break
    done
    if [ $GET = yes ]; then
      $SCRIPTS/get ${i#$PACKAGES}
    fi
  done
  exit 0
fi

mkdir -p .stamps/$1

if [ -f $PACKAGES/$1/url ]; then
  if [ -f .stamps/$1/get ]; then
    [ ! .stamps/$1/get -ot $PACKAGES/$1/url -o $AUTOUPDATE = no ] && exit 0
    if [ $AUTOUPDATE = ask ]; then
      echo "Package $1 is not up to date."
      echo -n "Do you want to download an up to date version ? (y/n) "
      read UPDATE
      [ "$UPDATE" != y ] && exit 0
    fi
  fi

  $SCRIPTS/checkdeps get

  rm -f .stamps/$1/get

  printf "%${INDENT}c GET      $1\n" >&$SILENT_OUT
  export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

  [ "$VERBOSE" != yes ] && WGET_OPT=-q

  mkdir -p $SOURCES/$1

  for i in `sed s%GEEXBOX_SRCS%$GEEXBOX_SRCS% $PACKAGES/$1/url`; do
    wget --passive-ftp -c $WGET_OPT -P $SOURCES/$1 $i
  done

  cp -p $PACKAGES/$1/url .stamps/$1/get
  rm -f .stamps/$1/unpack
  rm -f .stamps/$1/build
  rm -f .stamps/$1/install
fi
