#!/bin/sh

. config/options

if [ "$1" = generator ]; then
  cp -PR $ROOTFS/etc $INSTALL
  rm -rf $ROOTFS/etc
else
  rm -rf $INSTALL/etc
fi

mkdir -p $INSTALL/isolinux
cp -P $ROOTFS/boot/* $INSTALL
$SCRIPTS/initramfs image
$SCRIPTS/squashfs
if [ "$TARGET_ARCH" = i386 -o "$TARGET_ARCH" = x86_64 ]; then
  $SCRIPTS/installdev syslinux
  cp -PR $ROOT/$TOOLCHAIN/boot/* $INSTALL/isolinux
  $SCRIPTS/installdev grub-efi
  mkdir -p $INSTALL/EFI/boot
  cp -PR $ROOT/$TOOLCHAIN/share/EFI/* $INSTALL/EFI/boot
elif [ "$TARGET_ARCH" = powerpc -o "$TARGET_ARCH" = powerpc64 ]; then
  $SCRIPTS/installdev yaboot
  cp -PR $ROOT/$TOOLCHAIN/boot/* $INSTALL/isolinux
fi

exit 0
