#!/bin/sh

. config/options

$SCRIPTS/install linux image $1
[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs

if [ "$1" = generator ]; then
  cp -PR $ROOTFS/etc $INSTALL
  rm -rf $ROOTFS/etc
else
  rm -rf $INSTALL/etc
fi

$SCRIPTS/install initrd $1
$SCRIPTS/install syslinux $1
$SCRIPTS/install yaboot $1
