#!/bin/sh

. config/options

$SCRIPTS/install linux image $1
[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs
$SCRIPTS/install initrd $1
$SCRIPTS/install syslinux $1
$SCRIPTS/install yaboot $1
rm -rf $INSTALL/etc
