#!/bin/sh

. config/options

do_gzip () {
  GZIP="`which pigz`" || GZIP="`which gzip`"
  $GZIP -9 $INITRAMFS
}

do_lzma () {
  lzma -9 $INITRAMFS -S .gz
  mv $INITRAMFS.gz $INITRAMFS
}

$SCRIPTS/installdev busybox-init

INITRAMFS=$ROOT/$BUILD/initramfs/initrd

rm -rf $ROOT/$BUILD/initramfs
mkdir -p $ROOT/$BUILD/initramfs

# Create a CPIO InitRamfs archive
cd $ROOT/$TOOLCHAIN/share/initramfs
find . | cpio -o -H newc > $INITRAMFS
cd -

case $TARGET_ARCH in
  i386|x86_64)
    do_lzma
    cp -P $INITRAMFS $INSTALL/initrd
    ;;

  arm)
    do_gzip
    mkimage -A arm -O linux -T ramdisk -C gzip -n "$DISTRONAME Ramdisk" \
      -d $INITRAMFS.gz $BUILD/initramfs/uinitrd.gz
    mkdir -p $INSTALL/boot
    cp $BUILD/initrd/uinitrd.gz $INSTALL/boot
  ;;

  *)
    ;;
esac

exit 0
