#!/bin/sh

. config/options

if [ "$1" == "" ]; then
  echo "usage: $0 package_name"
  exit 1
fi

$SCRIPTS/build $@ || exit 2

if [ -f $PACKAGES/$1/install ]; then
  $PACKAGES/$1/install $@ || exit 3
else
  mkdir -p $INSTALL/usr/bin
  cp $BUILD/$1*/$1 $INSTALL/usr/bin || exit 4
fi
