#!/bin/sh

. config/path
. $CONFIG/options

$SCRIPTS/checkdeps || exit 1

export INSTALL=$INSTALLATOR_NAME/disk/GEEXBOX
rm -rf $INSTALLATOR_NAME
$SCRIPTS/gentree installator || exit 1

export INSTALL=$INSTALLATOR_NAME/disk
$SCRIPTS/gentree installator boot || exit 1

cp $INSTALLATOR/installator.sh $INSTALLATOR_NAME
cp -r $DOCS $INSTALLATOR_NAME
cp COPYING $INSTALLATOR_NAME/COPYING
cp VERSION $INSTALLATOR_NAME/VERSION
sed -i s/.*busybox.*// $INSTALLATOR_NAME/installator.sh
tar czf $INSTALLATOR_NAME.tar.gz $INSTALLATOR_NAME
rm -rf $INSTALLATOR_NAME
