#!/bin/sh

. config/path
. $CONFIG/options

$SCRIPTS/checkdeps || exit 1

export INSTALL=$INSTALLATOR_NAME/disk/GEEXBOX
rm -rf $INSTALLATOR_NAME

mkdir -p $INSTALL/sbin
cp $CONFIG/init $INSTALL/sbin

$SCRIPTS/install linux modules installator || exit 1
$SCRIPTS/install eject installator || exit 1
$SCRIPTS/install alsa installator || exit 1
$SCRIPTS/install tvout installator || exit 1
$SCRIPTS/install setcd installator || exit 1
$SCRIPTS/install MPlayer installator || exit 1
$SCRIPTS/install network installator || exit 1

tar cj -C $INSTALL -f $INSTALL/bin.tar.bz2 lib usr/bin usr/lib
rm -rf $INSTALL/lib $INSTALL/usr/bin $INSTALL/usr/lib

export INSTALL=$INSTALLATOR_NAME/disk
$SCRIPTS/install linux image installator || exit 1
$SCRIPTS/install initrd installator || exit 1
$SCRIPTS/install syslinux installator || exit 1

cp -r $INSTALLATOR/* $INSTALLATOR_NAME
cp -r $DOCS $INSTALLATOR_NAME
cp COPYING $INSTALLATOR_NAME/COPYING
cp VERSION $INSTALLATOR_NAME/VERSION
sed -i s/.*busybox.*// $INSTALLATOR_NAME/installator.sh
tar czf $INSTALLATOR_NAME.tar.gz $INSTALLATOR_NAME
rm -rf $INSTALLATOR_NAME
