#!/bin/sh

ARCH_SRC="http://download.geexbox.org/snapshots/geexbox-xbmc-imx6-utilite/latest/binaries.utilite"
ARCHIVE=`curl http://download.geexbox.org/snapshots/geexbox-xbmc-imx6-utilite/latest/binaries.utilite/ -s| grep tar.xz | cut -d'"' -f2`
mkdir -p /root/install-utilite/temp
wget http://download.openbricks.org/utilite/boot.scr -O /root/install-utilite/boot.scr
wget $ARCH_SRC/$ARCHIVE -O /root/install-utilite/$ARCHIVE
mount /dev/sda2 /root/install-utilite/temp
rm -rf /root/install-utilite/temp/*
mkdir /root/install-utilite/temp/boot
mount /dev/sda1 /root/install-utilite/temp/boot
rm -rf /root/install-utilite/temp/boot/*
tar --no-same-owner -xaf /root/install-utilite/$ARCHIVE -C /root/install-utilite/temp
cp /root/install-utilite/boot.scr /root/install-utilite/temp/boot/boot.scr
umount /dev/sda1
umount /dev/sda2
