#!/bin/sh

. config/options

$SCRIPTS/checkdeps build
$SCRIPTS/checkdeps iso

rm -rf $BUILD/iso
mkdir -p $BUILD/iso
export INSTALL=$BUILD/iso/GEEXBOX

$SCRIPTS/image "$1"

case $TARGET_ARCH in
  i386|x86_64)
    MKISOFS_ARCH="-no-emul-boot \
                  -boot-info-table \
                  -boot-load-size 4 \
                  -b GEEXBOX/boot/isolinux.bin \
                  -c GEEXBOX/boot/boot.catalog"
    ;;
  powerpc|powerpc64)
    MKISOFS_ARCH="-hfs \
                  -part \
                  -no-desktop \
                  -map $CONFIG/maps \
                  -hfs-volid GEEXBOX \
                  -hfs-bless $BUILD/iso/GEEXBOX/boot"
    ;;
esac

mkdir -p $BINROOT
mkisofs -quiet -no-pad -V GEEXBOX -volset GEEXBOX \
        -publisher "The GeeXboX team (www.geexbox.org)" \
        -p "The GeeXboX team (www.geexbox.org)" \
        -A "MKISOFS ISO 9660/HFS FILESYSTEM BUILDER" \
        -z -D -r -J -sort $CONFIG/sort $MKISOFS_ARCH \
        $BUILD/iso > $ISO

[ -f $BUILD/syslinux*/utils/isohybrid ] && $BUILD/syslinux*/utils/isohybrid $ISO

exit 0
