#!/bin/sh

. config/path
. $CONFIG/options

$SCRIPTS/checkdeps || exit 1

export INSTALL=$BUILD/iso/GEEXBOX
rm -rf $BUILD/iso
$SCRIPTS/gentree iso || exit 1

rm -rf $BUILD/ziso
mkdir -p $BUILD/ziso
mkzftree $INSTALL $BUILD/ziso/GEEXBOX

export INSTALL=$BUILD/ziso/GEEXBOX
$SCRIPTS/gentree iso boot || exit 1

mkisofs -quiet -no-pad -V GEEXBOX -volset GEEXBOX -P "The GeeXboX team (http://www.geexbox.org/)" -p "The GeeXboX team (http://www.geexbox.org/)" -A "MKISOFS ISO 9660/HFS FILESYSTEM BUILDER" -z -D -r -J -b GEEXBOX/boot/isolinux.bin -c GEEXBOX/boot/boot.catalog -no-emul-boot -boot-load-size 4 -boot-info-table $BUILD/ziso > $ISO
