#!/bin/sh

. config/options

( $SCRIPTS/checkdeps build && $SCRIPTS/checkdeps iso ) || exit 1

rm -rf $BUILD/iso
mkdir -p $BUILD/iso
export INSTALL=$BUILD/iso

$SCRIPTS/image "$1"

case $TARGET_ARCH in
  i386|x86_64)
    MKISOFS_ARCH="-no-emul-boot \
                  -boot-info-table \
                  -boot-load-size 4 \
                  -b isolinux/isolinux.bin \
                  -c isolinux/boot.catalog"
    ;;
  powerpc|powerpc64)
    MKISOFS_ARCH="-hfs \
                  -part \
                  -no-desktop \
                  -map $CONFIG/maps \
                  -hfs-volid $DISTRONAME_UC \
                  -hfs-bless $BUILD/iso/$DISTRODIR/boot"
    ;;
esac

mkdir -p $BINROOT
mkisofs -quiet -no-pad -V $DISTRONAME_UC -volset $DISTRONAME_UC \
        -publisher "The OpenBricks team (www.openbricks.org)" \
        -p "The OpenBricks team (www.openbricks.org)" \
        -A "MKISOFS ISO 9660/HFS FILESYSTEM BUILDER" \
        -z -D -r -J -sort $CONFIG/sort $MKISOFS_ARCH \
        $BUILD/iso > $ISO

[ -f $ROOT/$TOOLCHAIN/bin/isohybrid ] && $ROOT/$TOOLCHAIN/bin/isohybrid $ISO

exit 0
