#!/bin/sh

. config/options

LIB=$1
LIBA=$2
PROG=$3
SO=$4
PROG_SYMS=$5
LDSCRIPT="$ROOT/$SCRIPTS/ldscript.xs";

if [ ! -f $LIBA ]; then
  echo "ERROR $LIBA doesn't exists."
  exit 1
fi

for i in $PROG; do
  [ ! -f $LIB -o $i -nt $LIB -o $i -ot $LIBA ] && NEED_TO_STRIP=yes && break
done
[ "$NEED_TO_STRIP" != yes ] && exit 0

echo -n "stripping $LIB ..."

for i in $SO; do
  SO_SYMS="$SO_SYMS `$TARGET_NM --dynamic $i | sed -n 's/^........ [ABDGTW] \(..*\)/\1/p'`"
done

for i in $PROG; do
  if [ -f $i ]; then
    for j in `$TARGET_NM --dynamic $i | sed -n 's/^........ [BUV] \(..*\)/\1/p'`; do
      (echo "$SO_SYMS" | grep $j >/dev/null) || (echo "$PROG_SYMS" | grep $j >/dev/null) || PROG_SYMS="$PROG_SYMS $j"
    done
  fi
done

echo "INCLUDE $LDSCRIPT" > /tmp/ldscript
for i in $PROG_SYMS; do
 echo "EXTERN($i)" >> /tmp/ldscript
done

$TARGET_CC -s -Wl,-warn-common -shared -o $LIB -Wl,-soname,`basename $LIB` -Wl,--script=/tmp/ldscript $LIBA || exit 1

echo " done"

rm -f /tmp/ldscript
