#!/bin/sh

. config/path

LIB=$1
LIBA=$2
PROG=$3
SO=$4
PROG_SYMS=$5
LDSCRIPT="$ROOT/$SCRIPTS/ldscript.xs";

. config/path
UCGCC=`ls -d $ROOT/$BUILD/uClibc-*/build/usr/bin/gcc`

echo -n "stripping $LIB ..."

for i in $SO; do
  SO_SYMS="$SO_SYMS `nm --dynamic $i | sed -n 's/^........ [ABDGTW] \(..*\)/\1/p'`"
done

for i in $PROG; do
  if [ -f $i ]; then
    for j in `nm --dynamic $i | sed -n 's/^........ [BUV] \(..*\)/\1/p'`; do
      (echo "$SO_SYMS" | grep $j >/dev/null) || (echo "$PROG_SYMS" | grep $j >/dev/null) || PROG_SYMS="$PROG_SYMS $j"
    done
  fi
done

echo "INCLUDE $LDSCRIPT" > /tmp/ldscript
for i in $PROG_SYMS; do
 echo "EXTERN($i)" >> /tmp/ldscript
done

$UCGCC -s -Wl,-warn-common -shared -o $LIB -Wl,-soname,`basename $LIB` -Wl,--script=/tmp/ldscript $LIBA

echo " done"
