#!/bin/sh

. config/options

$SCRIPTS/kconfiginit

DEFCONFIG_PATH="$CONFIG/defconfigs"
DOT_CONFIG="`ls -d $ROOT/$BUILD_NOARCH/bst-kconfig-*`/.config"

die () {
  echo "Usage: $0 [defconfig filename]"
  exit 1
}

not_found () {
  echo "File not found: $CFG_FILENAME"
  exit 1
}

# check for valid config file
[ -z "$1" ]   && die

CFG_FILENAME="${DEFCONFIG_PATH}/$1.conf"

[ ! -f "$CFG_FILENAME" ] && not_found

echo ""
echo "########################################################################"
echo "##"
echo "## Loading configuration from:"
echo "##   ./${CFG_FILENAME}"
echo "##"
echo "########################################################################"
echo ""

cp -P ${CFG_FILENAME} ${DOT_CONFIG}

exit 0
