#!/bin/sh

. config/options

$SCRIPTS/installdev snowball-startupfiles
$SCRIPTS/installdev u-boot

rm -rf $BUILD/snowball
mkdir -p $BUILD/snowball
cp -PR $ROOT/$TOOLCHAIN/share/snowball-startupfiles/* $BUILD/snowball
cp -PR $ROOT/$TOOLCHAIN/share/u-boot/u-boot.bin $BUILD/snowball

(cd $BUILD/snowball; $ROOT/$TOOLCHAIN/bin/mksnowball startfiles.cfg out)
cp $BUILD/snowball/out $SNOWBALL_EMMC
