#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

$SCRIPTS/tarball

rm -rf $TARBALL_NAME $TARBALL_DIR
mkdir -p $TARBALL_DIR

cp -P $TBZ2_NAME $TARBALL_DIR
cp -P $SCRIPTS/omapsd $TARBALL_DIR

# build release tarball
tar cf $ROOT/$TARBALL_NAME -C $TARBALL_DIR .

rm -rf $TARBALL_DIR

exit 0
