#!/bin/sh

. config/options

add_control() {
  local KEY="$1"
  local VAL="$2"

  [ -n "$KEY" -a -n "$VAL" ] && \
    echo "${KEY}: $VAL" >> $INSTALL/CONTROL/control

  return 0
}

get_meta $1

if [ "$PKG_OPK_ARCH" = unsupported ]; then
  echo "$1 is not supported on $TARGET_ARCH, aborting"
  exit 1
fi

mkdir -p $PKGROOT
STAMP="$PKGROOT/$PKG_OPK"

if [ -f $STAMP -a $PACKAGES/$1/install -nt $STAMP ]; then
  $SCRIPTS/uninstall $1
  rm -f $STAMP
fi

if [ -f $STAMP ]; then
  echo "$1 is already packaged, skipping..." >&$VERBOSE_OUT
  exit 0
fi

if [ ! -f $PACKAGES/$1/install ]; then
  echo "$1 is not a runtime package, skipping..." >&$VERBOSE_OUT
  exit 0
fi

printf "%${INDENT}c PACKAGE  $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

rm -f $STAMP

export INSTALL="$PKGROOT/staging/$1"

rm -rf $INSTALL
mkdir -p $INSTALL/CONTROL

# build
$SCRIPTS/build $1

# package runtime deps
for p in $PKG_DEPENDS; do
  $SCRIPTS/package $p
done

# install to staging
if [ -d $PACKAGES/$1/init ]; then
  mkdir -p $INSTALL/etc/init
  cp $PACKAGES/$1/init/* $INSTALL/etc/init/
fi

#[ -x $PACKAGES/$1/install ] && 
$PACKAGES/$1/install $1 >&$VERBOSE_OUT

# build opk package
[ -d $PACKAGES/$1/package ] && cp -P $PACKAGES/$1/package/* $INSTALL/CONTROL

add_control "Package" "$PKG_NAME"
add_control "Version" "${PKG_VERSION}-${PKG_REV}"
add_control "Architecture" "$PKG_OPK_ARCH"
add_control "Depends" "$PKG_OPK_DEPENDS"
add_control "Priority" "$PKG_PRIORITY"
add_control "Section" "$PKG_SECTION"
add_control "Maintainer" "The GeeXboX Team (http://geexbox.org)"
add_control "Source" "http://hg.geexbox.org/geexbox"
add_control "Description" "$PKG_SHORTDESC"

if [ -n "$PKG_SHORTDESC" -a -n "$PKG_LONGDESC" ]; then
  echo "$PKG_LONGDESC" | fmt | sed 's/^/  /g' >> \
    $INSTALL/CONTROL/control
fi

opkg-build -c -O -o root -g root $INSTALL $PKGROOT >&$VERBOSE_OUT
