#!/bin/sh

cat << EOF
<html>
  <body>
    <table border="1" align="center">
      <tr align="center">
        <th>Package Name</td>
        <th>Package Version</td>
      </tr>
EOF

for pkg in $(ls packages/*/meta) ; do
  unset PKG_NAME PKG_VERSION
  . $pkg
  [ -z "${PKG_NAME}" -o -z "${PKG_VERSION}" ] && continue
  echo "       <tr align=\"center\">"
  echo "         <td>${PKG_NAME}</td>"
  echo "         <td>${PKG_VERSION}</td>"
  echo "       </tr>"
done

cat << EOF
    </table>
  </body>
</html>
EOF
