#!/bin/sh

[ "$1" != "ffmpeg" -a "$1" != "mplayer" ] && exit 1

echo "##################################################"
echo "####         $1 SVN Sources Packager          ####"
echo "##################################################"
echo

case $1 in
  ffmpeg)
    SERVER_URL=http://ffmpeg.org/releases
    ;;

  mplayer)
    SERVER_URL=http://www1.mplayerhq.hu/MPlayer/releases
    ;;
esac

wget $SERVER_URL/$1-export-snapshot.tar.bz2 \
  -O $1-export-`date +%Y-%m-%d`.tar.bz2

exit 0
