#!/bin/sh

for s in sources/*; do
  pkg=${s#sources/}

  if [ -d packages/$pkg ]; then    
    unset PKG_URL srcfiles
    srcfiles="`find $s -type f -print`"
    . packages/$pkg/meta
    for f in $srcfiles; do
      file=`basename $f`
      echo $PKG_URL|grep -qv $file && topurge="$topurge $f"
    done
  else
    # obsolete package sources
    topurge="$topurge $s"
  fi
done

rm -rf $topurge
