#!/bin/sh

for s in sources/*; do
  pkg=${s#sources/}

  if [ -d packages/$pkg ]; then    
    unset PKG_URL srcfiles
    srcfiles="`find $s -type f -print`"
    . packages/$pkg/meta
    for url in  $PKG_URL; do
      pkgfile=`echo $url | sed 's/.*\///'`
      for f in $srcfiles; do
        file=`basename $f`
        [ "$file" != "$pkgfile" ] && topurge="$topurge $f"
      done
    done
  else
    # obsolete package sources
    topurge="$topurge $s"
  fi
done

rm -rf $topurge
