#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

$SCRIPTS/flat "$1"

rm -rf $PXE_NAME
mkdir -p $PXE_NAME

cp -PR $FLAT_NAME/* $PXE_NAME

if [ "$TARGET_ARCH" = i386 ] || [ "$TARGET_ARCH" = x86_64 ]; then
  $SCRIPTS/installdev syslinux
  cp -PR $ROOT/$TOOLCHAIN/boot/* $PXE_NAME/boot
fi

chmod -R +r $PXE_NAME
