#!/bin/sh

. config/options

$SCRIPTS/checkdeps build

export INSTALL=$PXE_NAME
rm -rf $PXE_NAME
mkdir -p $PXE_NAME

$SCRIPTS/install linux image $1
$SCRIPTS/rootfs
$SCRIPTS/install initrd $1
$SCRIPTS/install syslinux $1
$SCRIPTS/install yaboot $1
rm -rf $INSTALL/etc

chmod -R +r $PXE_NAME
