#!/bin/sh

. config/options

do_usage() {
  echo "Usage:"
  echo "  $0 /path/to/image.iso"
  exit 1
}

$SCRIPTS/checkdeps qemu || exit 1

[ -z $1 ] && do_usage

[ $TARGET_ARCH = i386 ] && qemu -boot d -cdrom $1
[ $TARGET_ARCH = x86_64 ] && qemu-system-x86_64 -boot d -cdrom $1

exit 0
