#!/bin/sh

cat > config/Kconfig.remote <<EOF
# This file defines the remote and receiver configuration options

choice REMOTE
  prompt "Remote"
  default REMOTE_atiusb

EOF

remotes=`ls packages/lirc*/config/lircd* | grep ^\.*.conf$ | sed 's:^.*lircd_\(.*\)\.conf$:\1:g' | sort`

for remote in $remotes; do
  cat >> config/Kconfig.remote <<EOF
config REMOTE_${remote}
  bool "${remote}"
EOF
done

cat >> config/Kconfig.remote <<EOF

endchoice

choice RECEIVER
  prompt "Receiver"
  default RECEIVER_atiusb

EOF

receivers=`ls packages/lirc*/config/lircd* | grep -v ^\.*.conf$ | sed 's:^.*lircd_\(.*\)$:\1:g' | sort`

for receiver in $receivers; do
  cat >> config/Kconfig.remote <<EOF
config RECEIVER_${receiver}
  bool "${receiver}"
EOF
done

cat >> config/Kconfig.remote <<EOF

endchoice

config GX_REMOTE
  string
EOF

for remote in $remotes; do
  echo "  default \"${remote}\" if REMOTE_${remote}" >> config/Kconfig.remote
done

cat >> config/Kconfig.remote <<EOF

config GX_RECEIVER
  string
EOF

for receiver in $receivers; do
  echo "  default \"${receiver}\" if RECEIVER_${receiver}" >> config/Kconfig.remote
done
