#!/bin/sh

. config/options

DEFCONFIG_PATH="$CONFIG/defconfigs"
DOT_CONFIG="`ls -d $ROOT/$BUILD_NOARCH/bst-kconfig-*`/.config"

CFG_FILENAME="$FLAVOUR"

[ "$FLAVOUR" = geexbox ] && \
  CFG_FILENAME="${CFG_FILENAME}-${MEDIA_CENTER_FRONTEND}"

CFG_FILENAME="${CFG_FILENAME}-${TARGET_PLATFORM}"

[ -n "$TARGET_MACHINE" ] && \
  CFG_FILENAME="${CFG_FILENAME}-${TARGET_MACHINE}"

CFG_FILENAME="${CFG_FILENAME}.conf"

echo ""
echo "########################################################################"
echo "##"
echo "## Saving current configuration to:"
echo "##   ./${DEFCONFIG_PATH}/${CFG_FILENAME}"
echo "##"
echo "########################################################################"
echo ""

cp -P $DOT_CONFIG ./${DEFCONFIG_PATH}/${CFG_FILENAME}

exit 0
