#!/bin/sh

. config/options

[ -n "$BINROOT" ] || exit 1

mkdir -p $BINROOT
sed -e "s/^DEFAULT_TARGET=\"(undefined)\"/DEFAULT_TARGET=\"$TARGET_MACHINE\"/" $SCRIPTS/sdcard-template > $BINROOT/make-sdcard
chmod 775 $BINROOT/make-sdcard

exit 0
