#!/bin/sh

. config/options

IMAGE=$1
if [ -z "$IMAGE" ]; then
  IMAGE=$SNOWBALL_EMMC
  [ -r "$IMAGE" ] || $SCRIPTS/mksnowball
fi

$SCRIPTS/installdev riff

sudo LD_LIBRARY_PATH=$ROOT/$TOOLCHAIN/lib \
  $ROOT/$TOOLCHAIN/bin/riff \
  -c $ROOT/$TOOLCHAIN/share/riff/config \
  -m flash \
  -f $IMAGE
