#!/bin/sh

. config/options

$SCRIPTS/installdev squashfs

SQUASH_DIR=$ROOT/$BUILD/squashfs
SQUASH_IMG=$SQUASH_DIR/rootfs

rm -rf $SQUASH_DIR
mkdir -p $SQUASH_DIR
INSTALL=$BUILD/iso
cd $SQUASH_DIR
mkdir -p tmp
cp -PR $ROOTFS/* tmp
rm -rf tmp/boot
$ROOT/$TOOLCHAIN/bin/mksquashfs tmp $SQUASH_IMG -noappend -comp $COMPRESSION_METHOD -b 524288
mkdir -p $ROOT/$INSTALL
cp -P $SQUASH_IMG $ROOT/$INSTALL
cd -

exit 0
