#!/bin/sh

. config/options

$1 geexbox-$GEEXBOX_VERSION-*.iso \
   geexbox-generator-$GEEXBOX_VERSION*.tar.gz \
   geexbox-$GEEXBOX_VERSION.tar.bz2 \
   geexbox-$GEEXBOX_VERSION-full.tar \
   > geexbox-$GEEXBOX_VERSION.$1
