#!/bin/sh

. config/options

$1 $FLAVOUR-$GEEXBOX_VERSION-*.iso \
   $FLAVOUR-generator-$GEEXBOX_VERSION*.tar.gz \
   $FLAVOUR-$GEEXBOX_VERSION-lite.tar.bz2 \
   $FLAVOUR-$GEEXBOX_VERSION-full.tar \
   > $FLAVOUR-$GEEXBOX_VERSION.$1
