#!/bin/sh

. config/options

$1 $FLAVOUR-$DISTRO_VERSION-*.iso \
   $FLAVOUR-generator-$DISTRO_VERSION*.tar.gz \
   $FLAVOUR-$DISTRO_VERSION-lite.tar.bz2 \
   $FLAVOUR-$DISTRO_VERSION-full.tar \
   > $FLAVOUR-$DISTRO_VERSION.$1
