#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

rm -rf $TBZ2_NAME $TARBALL_DIR
mkdir -p $TARBALL_DIR

[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs

cp -PR $ROOTFS/* $TARBALL_DIR

. $CONFIG_MACHINE/meta

if [ -n "$MACHINE_XLOADER_CONFIG" ]; then
  $SCRIPTS/installdev x-loader
  mkdir -p $TARBALL_DIR/boot
  cp -P $ROOT/$TOOLCHAIN/share/x-loader/* $TARBALL_DIR/boot
fi

if [ -n "$MACHINE_UBOOT_CONFIG" ]; then
  $SCRIPTS/installdev u-boot
  mkdir -p $TARBALL_DIR/boot
  cp -P $ROOT/$TOOLCHAIN/share/u-boot/* $TARBALL_DIR/boot
fi

tar cpjf $TBZ2_NAME -C $TARBALL_DIR .

rm -rf $TARBALL_DIR

exit 0
