#!/bin/sh

. config/options

STAMP=$ROOTFS/var/lib/opkg/info/$1.control

[ ! -f $STAMP ] && exit 0

printf "%${INDENT}c UNINSTALL  $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

$ROOT/$TOOLCHAIN/bin/opkg --force-removal-of-dependent-packages \
                          --offline-root $ROOTFS \
                          remove $1 >&$VERBOSE_OUT
