#!/bin/sh

. config/options

STAMP=$ROOT/$TOOLCHAIN/var/lib/opkg/info/$1.control

[ ! -f $STAMP ] && exit 0

printf "%${INDENT}c UNINSTALLDEV  $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

$ROOT/$TOOLCHAIN/bin/opkg --force-removal-of-dependent-packages \
                          --offline-root $ROOT/$TOOLCHAIN \
                          remove $1 >&$VERBOSE_OUT
