#!/bin/sh

. config/options

STAMP=$ROOTFS/var/lib/opkg/info/$1.control

[ ! -f $STAMP ] && exit 0

set_title "UNINSTALL  $1"

$ROOT/$TOOLCHAIN/bin/opkg --force-removal-of-dependent-packages \
                          --offline-root $ROOTFS \
                          remove $1 >&$VERBOSE_OUT
