#!/bin/sh

. config/options

get_meta $1

STAMP=$DEVPKGROOT/$PKG_OPK_DEV

[ ! -f $STAMP ] && exit 0

printf "%${INDENT}c UNPACKAGEDEV  $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

$SCRIPTS/uninstalldev $1

rm -f $STAMP
