#!/bin/sh

. config/options

get_meta $1

STAMP=$PKGROOT/$PKG_OPK

[ ! -f $STAMP ] && exit 0

printf "%${INDENT}c UNPACKAGE  $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

$SCRIPTS/uninstall $1
$SCRIPTS/uninstall $1-dbg

rm -f $STAMP
rm -f $PKGROOT/$PKG_DBG_OPK
