#!/bin/sh

. config/options

do_usage() {
  echo "Usage:"
  echo "  $0 /path/to/image.iso"
  exit 1
}

$SCRIPTS/checkdeps vbox || exit 1

[ -z $1 ] && do_usage

ISO_IMAGE="$ROOT/$1"
ISO_UUID=$(uuid)
VBOX_IMAGE=/tmp/openbricks.vbox

[ -f $VBOX_IMAGE ] && rm -f $VBOX_IMAGE
cp -P utils/openbricks.vbox $VBOX_IMAGE
sed -i "s%__UUID__%$ISO_UUID%" $VBOX_IMAGE
sed -i "s%__LOCATION__%$ISO_IMAGE%" $VBOX_IMAGE
vboxmanage list vms | grep -q OpenBricks
[ $? -ne 0 ] && vboxmanage registervm $VBOX_IMAGE
virtualbox --startvm $VBOX_IMAGE

exit 0
