#!/bin/sh

. config/options

do_usage() {
  echo "Usage:"
  echo "  $0 /path/to/image.iso"
  exit 1
}

$SCRIPTS/checkdeps vbox || exit 1

[ -z $1 ] && do_usage

ISO_IMAGE="$ROOT/$1"
if [ -x /usr/bin/uuid ]; then
  ISO_UUID=$(uuid)
elif [ -x /usr/bin/uuidgen ]; then
  ISO_UUID=$(uuidgen)
else
  echo "Please install the uuid or uuidgen package."
  exit 1
fi
VBOX_IMAGE=/tmp/openbricks.vbox

[ -f $VBOX_IMAGE ] && rm -f $VBOX_IMAGE
cp -P utils/openbricks.vbox $VBOX_IMAGE
sed -i "s%__UUID__%$ISO_UUID%" $VBOX_IMAGE
sed -i "s%__LOCATION__%$ISO_IMAGE%" $VBOX_IMAGE
vboxmanage list vms | grep -q OpenBricks || vboxmanage registervm $VBOX_IMAGE
virtualbox --startvm $VBOX_IMAGE

exit 0
