#!/bin/sh

. config/options

if [ "$1" = build ]; then
  $SCRIPTS/checkdeps build

  make iso
  rm -rf $VMX_NAME
  mkdir -p $VMX_NAME
  cp $CONFIG/geexbox-vmx.vmx $VMX_NAME
  cp $CONFIG/geexbox-vmx.nvram $VMX_NAME
  cp $CONFIG/geexbox-hdd* $VMX_NAME
  sed -i "s%ide1:0.fileName.*%ide1:0.fileName = \"$ROOT/$ISO\"%" $VMX_NAME/geexbox-vmx.vmx
elif [ "$1" = play ]; then
  $SCRIPTS/checkdeps vmx
  vmplayer $VMX_NAME/geexbox-vmx.vmx
fi
