void menu(const char *);
void mplayerMenu(const char *);
void playFile(const char *);
void playDir(const char *);
void execMplayerCmd(const char *);
void execSystemCmd(const char *);
const char * getDir();
void setDir(const char *dir);
void setFileContent(const char *, const char *);
const char * getFileContent(const char *);
void cmdSystem(const char *);
void cmdMplayer(const char *);
