/* language */
#define PLAY_FILE "Play this file"
#define PLAY_DIR "Play this directory"
#define PAUSE "Pause"
#define STOP "Stop"
#define REBOOT "Reboot GeeXboX"
#define POWEROFF "Power Off GeeXboX"
#define PLAY_NEXT "Play next track [SHIFT + ALT + n]"
#define PLAY_PREVIOUS "Play previous track [SHIFT + ALT + p]"
#define SEEK_FW "Seek 30 seconds forward"
#define SEEK_BW "Seek 30 seconds backward"
